export const ITALIAN_PROVINCE_BY_CITY: Record<string, string> = {
  'agrigento': 'AG',
  'alessandria': 'AL',
  'ancona': 'AN',
  'aosta': 'AO',
  'arezzo': 'AR',
  'ascoli piceno': 'AP',
  'asti': 'AT',
  'avellino': 'AV',
  'bari': 'BA',
  'barletta': 'BT',
  'andria': 'BT',
  'trani': 'BT',
  'belluno': 'BL',
  'benevento': 'BN',
  'bergamo': 'BG',
  'biella': 'BI',
  'bologna': 'BO',
  'bolzano': 'BZ',
  'brescia': 'BS',
  'brindisi': 'BR',
  'cagliari': 'CA',
  'caltanissetta': 'CL',
  'campobasso': 'CB',
  'carbonia': 'CI',
  'iglesias': 'CI',
  'caserta': 'CE',
  'catanzaro': 'CZ',
  'chieti': 'CH',
  'como': 'CO',
  'cosenza': 'CS',
  'cremona': 'CR',
  'crotone': 'KR',
  'cuneo': 'CN',
  'enna': 'EN',
  'fermo': 'FM',
  'ferrara': 'FE',
  'firenze': 'FI',
  'florence': 'FI',
  'foggia': 'FG',
  'forlì': 'FC',
  'cesena': 'FC',
  'frosinone': 'FR',
  'genova': 'GE',
  'genoa': 'GE',
  'gorizia': 'GO',
  'grosseto': 'GR',
  'imperia': 'IM',
  'isernia': 'IS',
  'la spezia': 'SP',
  'l\'aquila': 'AQ',
  'laquila': 'AQ',
  'latina': 'LT',
  'lecce': 'LE',
  'lecco': 'LC',
  'livorno': 'LI',
  'lodi': 'LO',
  'lucca': 'LU',
  'macerata': 'MC',
  'mantova': 'MN',
  'massa': 'MS',
  'carrara': 'MS',
  'matera': 'MT',
  'medio campidano': 'VS',
  'sanluri': 'VS',
  'villacidro': 'VS',
  'messina': 'ME',
  'milano': 'MI',
  'milan': 'MI',
  'modena': 'MO',
  'monza': 'MB',
  'napoli': 'NA',
  'naples': 'NA',
  'novara': 'NO',
  'nuoro': 'NU',
  'ogliastra': 'OG',
  'lanusei': 'OG',
  'tortolì': 'OG',
  'olbia': 'OT',
  'tempio pausania': 'OT',
  'oristano': 'OR',
  'padova': 'PD',
  'padua': 'PD',
  'palermo': 'PA',
  'parma': 'PR',
  'pavia': 'PV',
  'perugia': 'PG',
  'pesaro': 'PU',
  'urbino': 'PU',
  'pescara': 'PE',
  'piacenza': 'PC',
  'pisa': 'PI',
  'pistoia': 'PT',
  'pordenone': 'PN',
  'potenza': 'PZ',
  'prato': 'PO',
  'ragusa': 'RG',
  'ravenna': 'RA',
  'reggio calabria': 'RC',
  'reggio emilia': 'RE',
  'rieti': 'RI',
  'rimini': 'RN',
  'roma': 'RM',
  'rome': 'RM',
  'rovigo': 'RO',
  'salerno': 'SA',
  'sassari': 'SS',
  'savona': 'SV',
  'siena': 'SI',
  'siracusa': 'SR',
  'sondrio': 'SO',
  'taranto': 'TA',
  'teramo': 'TE',
  'terni': 'TR',
  'torino': 'TO',
  'turin': 'TO',
  'trapani': 'TP',
  'trento': 'TN',
  'trent': 'TN',
  'treviso': 'TV',
  'trieste': 'TS',
  'udine': 'UD',
  'varese': 'VA',
  'venezia': 'VE',
  'venice': 'VE',
  'verbania': 'VB',
  'vercelli': 'VC',
  'verona': 'VR',
  'vibo valentia': 'VV',
  'vicenza': 'VI',
  'viterbo': 'VT'
};

export const ITALIAN_PROVINCE_BY_REGION: Record<string, string> = {
  'lazio': 'RM',
  'lombardia': 'MI',
  'lombardy': 'MI',
  'campania': 'NA',
  'piemonte': 'TO',
  'piedmont': 'TO',
  'sicilia': 'PA',
  'sicily': 'PA',
  'veneto': 'VE',
  'emilia-romagna': 'BO',
  'emilia romagna': 'BO',
  'toscana': 'FI',
  'tuscany': 'FI',
  'puglia': 'BA',
  'apulia': 'BA',
  'liguria': 'GE',
  'calabria': 'RC',
  'sardegna': 'CA',
  'sardinia': 'CA',
  'marche': 'AN',
  'abruzzo': 'AQ',
  'umbria': 'PG',
  'friuli-venezia giulia': 'TS',
  'friuli venezia giulia': 'TS',
  'trentino-alto adige': 'TN',
  'trentino alto adige': 'TN',
  'molise': 'CB',
  'basilicata': 'PZ',
  'valle d\'aosta': 'AO',
  'valle daosta': 'AO',
  'vda': 'AO'
};

export function resolveItalianProvince(city: string, stateName: string): string {
  const cityKey = (city || '').toLowerCase().trim();
  if (ITALIAN_PROVINCE_BY_CITY[cityKey]) return ITALIAN_PROVINCE_BY_CITY[cityKey];
  
  // Try partial city names or compound city names
  for (const [name, code] of Object.entries(ITALIAN_PROVINCE_BY_CITY)) {
    if (cityKey.includes(name) || name.includes(cityKey)) {
      return code;
    }
  }

  const cleanedState = (stateName || '').trim();
  const numericMap: Record<string, string> = {
    '25': 'MI',
    '63': 'NA',
    '72': 'SA',
  };
  if (numericMap[cleanedState]) return numericMap[cleanedState];

  const regionKey = cleanedState.toLowerCase();
  if (ITALIAN_PROVINCE_BY_REGION[regionKey]) return ITALIAN_PROVINCE_BY_REGION[regionKey];

  if (/^[A-Z]{2}$/.test(cleanedState.toUpperCase())) {
    return cleanedState.toUpperCase();
  }

  return cleanedState.substring(0, 2).toUpperCase();
}
